### ISSUE TITLE
Compilation error in `materializeRecursively` call when upgrading to 1.34.3 version

### ISSUE THREAD

**Issue by plokhotnyuk** [AVSystem/scala-commons#94]
It was detected by PR from @scala-steward https://github.com/plokhotnyuk/jsoniter-scala/pull/201

Compilation error message is: 
```
[error] Error while emitting AVSystemCodecs.scala
[error] value deferred$macro$124
```

It fails at the following line, when generating a codec for the GeoJSON type: 
https://github.com/plokhotnyuk/jsoniter-scala/blob/a1dfb1355f80ae0927b2809bf9aab4062a6ed836/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/macros/AVSystemCodecs.scala#L55

**Comment by ghik** [comment]
Thanks, this should be fixed in 1.34.4. 
Recursive materialization was never really a preferred technique for us so its tests got a bit neglected...
